const apartmentsData = [
    {
      name: "The Axis Apartments",
      address: "350 Nathan Ln N, Plymouth, MN 55441",
      phone: "(763)-445-2299",
      beds: "1 - 2",
      sqFt: "",
      baths: "1 - 1",
      type: "Affordable Luxury",
      priceRange: "$1,592 - $2,792",
      deal: "One Month Free",
      image: "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1920/s3/2/20597/the_axis_plymouth_mn_exterior_5_large_optimized.jpg",
      companyWebsite: "https://www.move2theaxis.com/floorplans",
    },
    {
      name: "Lucille",
      address: "1025 MAIN ST NE, MINNEAPOLIS, MN 55413",
      phone: "612-643-5141",
      beds: "Studio - 2",
      sqFt: "650 - 850",
      baths: "1 - 1",
      type: "Apartment, Affordable",
      priceRange: "$1,295 - $3,495",
      deal: "Free Rent Until 2024",
      image: "https://image1.apartmentfinder.com/i2/xpXqq5fWoiB78s5xY5VnDB16m9scBexxHkOkO1Pa2Ek/116/lucille-minneapolis-mn-building-exterior-front.jpg",
      companyWebsite: "https://lucillempls.com/floor-plans",
    },
    {
      name: "The Laker Apartments",
      address: "2500 2nd St NE, Minneapolis, MN 55418",
      phone: "(612) 491-7731",
      beds: "Studio - 3",
      sqFt: "550 - 800",
      baths: "1 - 1",
      type: "Apartment, Affordable",
      priceRange: "$1,288 - $2,996",
      deal: "Two Months Free Rent",
      image: "https://image1.apartmentfinder.com/i2/FlKFIApvMgTUQ3f8mgHu6Ka72p8uBytmiL8UUWmM9ho/116/the-laker-minneapolis-mn-primary-photo.jpg",
      companyWebsite: "https://thelakermpls.com/floor-plans/",
    },
    {
      name: "The Station at Malcolm Yards Apartments",
      address: "485 Malcolm Ave SE, Minneapolis, MN 55414",
      phone: "(612) 682-0359",
      beds: "Studio - 2 Beds",
      sqFt: "550 - 800",
      baths: "1 - 1",
      type: "Apartment, Affordable",
      priceRange: "$1,180 - $2,315",
      deal: "One Month Free Rent ",
      image: "https://resource.rentcafe.com/image/upload/q_auto,f_auto,c_limit,w_1920/s3/2/23042/deck.jpg",
      companyWebsite: "https://www.malcolmstationapartments.com/availableunits",
    },
    {
      name: "Landsby on Penn",
      address: "6200 Penn Ave S, Richfield, MN 55423",
      phone: "612-999-2775",
      beds: "Studio - 3",
      sqFt: "550 - 800",
      baths: "1 - 1",
      type: "Apartment, Affordable",
      priceRange: "$1,373 - $4,001",
      deal: "Up to Two Months Free Rent",
      image: "https://landsbyonpenn.com/wp-content/uploads/2022/11/220714_Landsby_S_001-2-768x512.jpg",
      companyWebsite: "https://landsbyonpenn.com/floor-plans/",
    },
    {
      name: "Birke",
      address: "11700 Wayzata Blvd, Minnetonka, MN 55305",
      phone: "952-243-4683",
      beds: "Studio - 3",
      sqFt: "550 - 800",
      baths: "1 - 1",
      type: "Apartment, Affordable",
      priceRange: "$1,099 - $1,299",
      deal: "One Month Free Rent",
      image: "https://birkeminnetonka.com/wp-content/uploads/2023/01/Birke_210916-12-1030x687.jpg",
      companyWebsite: "https://birkeminnetonka.com/floor-plans/",
    },
  ];
  
  export default apartmentsData;
  